### ISSUE TITLE
Error YelpParser line 60 // no JSON data?

### ISSUE THREAD

**Issue by YtGz** [MasterMoritz/scraper#18]
Parsing Yelp API
Exception: API Error with yelp call
java.lang.IndexOutOfBoundsException: Index: 284, Size: 284
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.eclipsesource.json.JsonArray.get(JsonArray.java:416)
	at core.YelpParser.parseFromAPIs(YelpParser.java:60)
	at core.Main.updateRestaurantDatabase(Main.java:254)
	at core.Main$2.run(Main.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Gogeta05** [comment]
Bin mitm Andi drun, mir schaugn mol

**Comment by Gogeta05** [comment]
Ka. woher das kommt. Andi hat des nit, i huns a - lokal und am Server
Wir verwenden jetzt einfach eine aktuelle R DB von Andi (gerade vorhin geparst), dann würde der nächste Durchlauf erst in 5 TAgen sein und der Fehler wird umgangen und guat isch.
